// DNA file entry point. Detects the vendor from the file's contents,
// dispatches to the right parser, and unzips on the fly if needed.
//
// AncestryDNA users typically download a `.zip` containing a single `.txt`
// file. We accept either, plus a raw `.txt`/`.csv` if they've already
// extracted it. Everything happens in-browser — files never leave the page.
//
// Public API:
//   parseDnaFile(File)          — convenience: read + detect + parse
//   readDnaFileToText(File)     — extract just the unzipped text
//   parseDnaText(text, name)    — parse text we already have (e.g. from
//                                 storage), no file I/O

import { unzipSync, strFromU8 } from 'fflate';
import { isAncestryFile, parseAncestry } from './vendors/ancestry.js';

export async function parseDnaFile(file) {
  const text = await readDnaFileToText(file);
  return parseDnaText(text, file.name);
}

export function parseDnaText(text, filename = '') {
  if (isAncestryFile(text)) {
    return parseAncestry(text, filename);
  }

  if (/^# This data file generated by 23andMe/m.test(text.slice(0, 2000))) {
    throw new Error(
      '23andMe support is on the roadmap but not in this version. ' +
      'For now, please use an AncestryDNA file.'
    );
  }

  throw new Error(
    'Unrecognized DNA file format. AncestryDNA is supported in this version.'
  );
}

export async function readDnaFileToText(file) {
  const lower = file.name.toLowerCase();

  if (lower.endsWith('.zip')) {
    const buffer = new Uint8Array(await file.arrayBuffer());
    let entries;
    try {
      entries = unzipSync(buffer);
    } catch (err) {
      throw new Error(`Couldn't unzip "${file.name}": ${err.message || err}`);
    }
    let largestName = null;
    let largestData = null;
    let largestSize = -1;
    for (const [name, data] of Object.entries(entries)) {
      const lowName = name.toLowerCase();
      if (!lowName.endsWith('.txt') && !lowName.endsWith('.csv')) continue;
      if (data.length > largestSize) {
        largestSize = data.length;
        largestName = name;
        largestData = data;
      }
    }
    if (!largestData) {
      throw new Error(`No .txt or .csv file found inside "${file.name}".`);
    }
    return strFromU8(largestData);
  }

  return await file.text();
}
